import type { Product } from './types';

export const MOCK_PRODUCTS: Product[] = [
  // Flower (15 products)
  {
    id: '1',
    sku: 'FL-001',
    name: 'Purple Haze',
    category: 'flower',
    description: 'A legendary sativa strain with uplifting effects and a sweet, earthy aroma.',
    thcPercentage: 22,
    cbdPercentage: 1,
    price: 180,
    stockQuantity: 50,
    imageUrl: '/images/placeholder-product.png',
    imageUrls: ['/images/placeholder-product.png'],
    strainType: 'sativa',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '2',
    sku: 'FL-002',
    name: 'OG Kush',
    category: 'flower',
    description: 'Classic indica-dominant hybrid with earthy pine notes and relaxing effects.',
    thcPercentage: 24,
    cbdPercentage: 0.5,
    price: 200,
    stockQuantity: 45,
    imageUrl: '/images/placeholder-product.png',
    imageUrls: ['/images/placeholder-product.png'],
    strainType: 'hybrid',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '3',
    sku: 'FL-003',
    name: 'Northern Lights',
    category: 'flower',
    description: 'Pure indica strain known for its powerful body high and sweet spicy aroma.',
    thcPercentage: 18,
    cbdPercentage: 1,
    price: 170,
    stockQuantity: 60,
    imageUrl: '/images/placeholder-product.png',
    imageUrls: ['/images/placeholder-product.png'],
    strainType: 'indica',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '4',
    sku: 'FL-004',
    name: 'Sour Diesel',
    category: 'flower',
    description: 'Energizing sativa with a pungent diesel aroma and creative effects.',
    thcPercentage: 20,
    cbdPercentage: 0.3,
    price: 190,
    stockQuantity: 40,
    imageUrl: '/images/placeholder-product.png',
    imageUrls: ['/images/placeholder-product.png'],
    strainType: 'sativa',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '5',
    sku: 'FL-005',
    name: 'Blue Dream',
    category: 'flower',
    description: 'Balanced hybrid with sweet berry flavors and gentle cerebral high.',
    thcPercentage: 19,
    cbdPercentage: 2,
    price: 185,
    stockQuantity: 55,
    imageUrl: '/images/placeholder-product.png',
    imageUrls: ['/images/placeholder-product.png'],
    strainType: 'hybrid',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '6',
    sku: 'FL-006',
    name: 'Jack Herer',
    category: 'flower',
    description: 'Sativa-dominant strain named after the cannabis activist, known for clarity.',
    thcPercentage: 23,
    cbdPercentage: 0.7,
    price: 195,
    stockQuantity: 35,
    imageUrl: '/images/placeholder-product.png',
    imageUrls: ['/images/placeholder-product.png'],
    strainType: 'sativa',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '7',
    sku: 'FL-007',
    name: 'Granddaddy Purple',
    category: 'flower',
    description: 'Potent indica with grape and berry flavors, perfect for evening relaxation.',
    thcPercentage: 21,
    cbdPercentage: 1.2,
    price: 205,
    stockQuantity: 30,
    imageUrl: '/images/placeholder-product.png',
    imageUrls: ['/images/placeholder-product.png'],
    strainType: 'indica',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '8',
    sku: 'FL-008',
    name: 'White Widow',
    category: 'flower',
    description: 'Balanced hybrid covered in crystal resin, energizing and euphoric.',
    thcPercentage: 20,
    cbdPercentage: 0.6,
    price: 180,
    stockQuantity: 50,
    imageUrl: '/images/placeholder-product.png',
    imageUrls: ['/images/placeholder-product.png'],
    strainType: 'hybrid',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '9',
    sku: 'FL-009',
    name: 'Girl Scout Cookies',
    category: 'flower',
    description: 'Indica-dominant hybrid with sweet and earthy flavors, deeply relaxing.',
    thcPercentage: 25,
    cbdPercentage: 0.9,
    price: 210,
    stockQuantity: 25,
    imageUrl: '/images/placeholder-product.png',
    imageUrls: ['/images/placeholder-product.png'],
    strainType: 'hybrid',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '10',
    sku: 'FL-010',
    name: 'Amnesia Haze',
    category: 'flower',
    description: 'Award-winning sativa with citrus flavors and powerful cerebral effects.',
    thcPercentage: 22,
    cbdPercentage: 0.4,
    price: 200,
    stockQuantity: 40,
    imageUrl: '/images/placeholder-product.png',
    imageUrls: ['/images/placeholder-product.png'],
    strainType: 'sativa',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '11',
    sku: 'FL-011',
    name: 'Pineapple Express',
    category: 'flower',
    description: 'Hybrid strain with tropical flavors and energizing, creative effects.',
    thcPercentage: 19,
    cbdPercentage: 0.8,
    price: 185,
    stockQuantity: 45,
    imageUrl: '/images/placeholder-product.png',
    imageUrls: ['/images/placeholder-product.png'],
    strainType: 'hybrid',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '12',
    sku: 'FL-012',
    name: 'Durban Poison',
    category: 'flower',
    description: 'Pure South African sativa with sweet smell and energetic, uplifting effects.',
    thcPercentage: 24,
    cbdPercentage: 0.5,
    price: 195,
    stockQuantity: 35,
    imageUrl: '/images/placeholder-product.png',
    imageUrls: ['/images/placeholder-product.png'],
    strainType: 'sativa',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '13',
    sku: 'FL-013',
    name: 'Bubba Kush',
    category: 'flower',
    description: 'Heavy indica with chocolate and coffee notes, deeply relaxing.',
    thcPercentage: 22,
    cbdPercentage: 1.5,
    price: 190,
    stockQuantity: 40,
    imageUrl: '/images/placeholder-product.png',
    imageUrls: ['/images/placeholder-product.png'],
    strainType: 'indica',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '14',
    sku: 'FL-014',
    name: 'Super Lemon Haze',
    category: 'flower',
    description: 'Sativa-dominant with zesty lemon flavor and energetic high.',
    thcPercentage: 21,
    cbdPercentage: 0.6,
    price: 200,
    stockQuantity: 30,
    imageUrl: '/images/placeholder-product.png',
    imageUrls: ['/images/placeholder-product.png'],
    strainType: 'sativa',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '15',
    sku: 'FL-015',
    name: 'Wedding Cake',
    category: 'flower',
    description: 'Indica-dominant hybrid with sweet, vanilla flavors and calming effects.',
    thcPercentage: 25,
    cbdPercentage: 0.7,
    price: 215,
    stockQuantity: 20,
    imageUrl: '/images/placeholder-product.png',
    imageUrls: ['/images/placeholder-product.png'],
    strainType: 'hybrid',
    isActive: true,
    createdAt: new Date().toISOString(),
  },

  // Edibles (15 products)
  {
    id: '16',
    sku: 'ED-001',
    name: 'Cannabis Gummies - Mixed Berry',
    category: 'edibles',
    description: 'Delicious mixed berry gummies, 10mg THC per piece, 10 pieces per pack.',
    thcPercentage: 10,
    cbdPercentage: 0,
    price: 120,
    stockQuantity: 100,
    imageUrl: '/images/placeholder-product.png',
    imageUrls: ['/images/placeholder-product.png'],
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '17',
    sku: 'ED-002',
    name: 'Dark Chocolate Bar 100mg',
    category: 'edibles',
    description: 'Premium dark chocolate infused with 100mg THC, breakable into 10 pieces.',
    thcPercentage: 10,
    cbdPercentage: 0,
    price: 150,
    stockQuantity: 80,
    imageUrl: '/images/placeholder-product.png',
    imageUrls: ['/images/placeholder-product.png'],
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '18',
    sku: 'ED-003',
    name: 'CBD Gummies - Tropical',
    category: 'edibles',
    description: 'Tropical flavored gummies with 25mg CBD per piece, great for relaxation.',
    thcPercentage: 0,
    cbdPercentage: 25,
    price: 100,
    stockQuantity: 120,
    imageUrl: '/images/placeholder-product.png',
    imageUrls: ['/images/placeholder-product.png'],
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '19',
    sku: 'ED-004',
    name: 'Cannabis Cookies - Double Chocolate',
    category: 'edibles',
    description: 'Homemade-style cookies, 50mg THC per cookie, pack of 2.',
    thcPercentage: 50,
    cbdPercentage: 0,
    price: 130,
    stockQuantity: 60,
    imageUrl: '/images/placeholder-product.png',
    imageUrls: ['/images/placeholder-product.png'],
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '20',
    sku: 'ED-005',
    name: 'Mango Chews',
    category: 'edibles',
    description: 'Chewy mango squares, 5mg THC each, perfect for microdosing.',
    thcPercentage: 5,
    cbdPercentage: 0,
    price: 90,
    stockQuantity: 150,
    imageUrl: '/images/placeholder-product.png',
    imageUrls: ['/images/placeholder-product.png'],
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '21',
    sku: 'ED-006',
    name: 'Mint Chocolate Truffles',
    category: 'edibles',
    description: 'Gourmet chocolate truffles with mint, 15mg THC per truffle, 4 pack.',
    thcPercentage: 15,
    cbdPercentage: 0,
    price: 140,
    stockQuantity: 70,
    imageUrl: '/images/placeholder-product.png',
    imageUrls: ['/images/placeholder-product.png'],
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '22',
    sku: 'ED-007',
    name: 'Sour Watermelon Slices',
    category: 'edibles',
    description: 'Sour sugar coated watermelon gummies, 10mg THC per piece.',
    thcPercentage: 10,
    cbdPercentage: 0,
    price: 115,
    stockQuantity: 90,
    imageUrl: '/images/placeholder-product.png',
    imageUrls: ['/images/placeholder-product.png'],
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '23',
    sku: 'ED-008',
    name: 'Caramel Popcorn',
    category: 'edibles',
    description: 'Sweet and salty caramel popcorn, 100mg THC total per bag.',
    thcPercentage: 10,
    cbdPercentage: 0,
    price: 125,
    stockQuantity: 50,
    imageUrl: '/images/placeholder-product.png',
    imageUrls: ['/images/placeholder-product.png'],
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '24',
    sku: 'ED-009',
    name: 'Lemon Drops',
    category: 'edibles',
    description: 'Hard candy lemon drops, 5mg THC each, 20 pieces per container.',
    thcPercentage: 5,
    cbdPercentage: 0,
    price: 95,
    stockQuantity: 110,
    imageUrl: '/images/placeholder-product.png',
    imageUrls: ['/images/placeholder-product.png'],
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '25',
    sku: 'ED-010',
    name: 'Peanut Butter Cups',
    category: 'edibles',
    description: 'Classic peanut butter cups infused with cannabis, 25mg THC per cup.',
    thcPercentage: 25,
    cbdPercentage: 0,
    price: 160,
    stockQuantity: 45,
    imageUrl: '/images/placeholder-product.png',
    imageUrls: ['/images/placeholder-product.png'],
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '26',
    sku: 'ED-011',
    name: 'Peach Rings',
    category: 'edibles',
    description: 'Sweet peach flavored gummy rings, 10mg THC per ring.',
    thcPercentage: 10,
    cbdPercentage: 0,
    price: 110,
    stockQuantity: 100,
    imageUrl: '/images/placeholder-product.png',
    imageUrls: ['/images/placeholder-product.png'],
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '27',
    sku: 'ED-012',
    name: 'Brownie Bites',
    category: 'edibles',
    description: 'Fudgy brownie bites, 30mg THC per bite, 3 per package.',
    thcPercentage: 30,
    cbdPercentage: 0,
    price: 145,
    stockQuantity: 55,
    imageUrl: '/images/placeholder-product.png',
    imageUrls: ['/images/placeholder-product.png'],
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '28',
    sku: 'ED-013',
    name: 'Honey Sticks',
    category: 'edibles',
    description: 'Pure honey infused with cannabis, 10mg THC per stick, 5 pack.',
    thcPercentage: 10,
    cbdPercentage: 0,
    price: 105,
    stockQuantity: 85,
    imageUrl: '/images/placeholder-product.png',
    imageUrls: ['/images/placeholder-product.png'],
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '29',
    sku: 'ED-014',
    name: 'Coconut Macaroons',
    category: 'edibles',
    description: 'Chewy coconut macaroons dipped in chocolate, 20mg THC each.',
    thcPercentage: 20,
    cbdPercentage: 0,
    price: 135,
    stockQuantity: 40,
    imageUrl: '/images/placeholder-product.png',
    imageUrls: ['/images/placeholder-product.png'],
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '30',
    sku: 'ED-015',
    name: 'Blueberry Muffins',
    category: 'edibles',
    description: 'Fresh-baked style muffins with real blueberries, 40mg THC per muffin.',
    thcPercentage: 40,
    cbdPercentage: 0,
    price: 155,
    stockQuantity: 35,
    imageUrl: '/images/placeholder-product.png',
    imageUrls: ['/images/placeholder-product.png'],
    isActive: true,
    createdAt: new Date().toISOString(),
  },

  // Paraphernalia (10 products)
  {
    id: '31',
    sku: 'PR-001',
    name: 'Glass Bong - 12 inch',
    category: 'paraphernalia',
    description: 'Classic glass water pipe with ice catcher and percolator for smooth hits.',
    price: 450,
    stockQuantity: 20,
    imageUrl: '/images/placeholder-product.png',
    imageUrls: ['/images/placeholder-product.png'],
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '32',
    sku: 'PR-002',
    name: 'Rolling Papers - King Size',
    category: 'paraphernalia',
    description: 'Premium slow-burning rolling papers, pack of 32 leaves.',
    price: 45,
    stockQuantity: 200,
    imageUrl: '/images/placeholder-product.png',
    imageUrls: ['/images/placeholder-product.png'],
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '33',
    sku: 'PR-003',
    name: 'Herb Grinder - 4 Chamber',
    category: 'paraphernalia',
    description: 'Aluminum herb grinder with 4 chambers and magnetic lid.',
    price: 250,
    stockQuantity: 75,
    imageUrl: '/images/placeholder-product.png',
    imageUrls: ['/images/placeholder-product.png'],
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '34',
    sku: 'PR-004',
    name: 'Glass Pipe - Spoon',
    category: 'paraphernalia',
    description: 'Handmade glass spoon pipe with vibrant colors.',
    price: 180,
    stockQuantity: 50,
    imageUrl: '/images/placeholder-product.png',
    imageUrls: ['/images/placeholder-product.png'],
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '35',
    sku: 'PR-005',
    name: 'Storage Jar Set - 3 Pack',
    category: 'paraphernalia',
    description: 'Airtight glass jars with UV protection, perfect for storing herbs.',
    price: 200,
    stockQuantity: 60,
    imageUrl: '/images/placeholder-product.png',
    imageUrls: ['/images/placeholder-product.png'],
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '36',
    sku: 'PR-006',
    name: 'Rolling Tray - Medium',
    category: 'paraphernalia',
    description: 'Metal rolling tray with raised edges and curved corners.',
    price: 120,
    stockQuantity: 80,
    imageUrl: '/images/placeholder-product.png',
    imageUrls: ['/images/placeholder-product.png'],
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '37',
    sku: 'PR-007',
    name: 'Lighter - Clipper',
    category: 'paraphernalia',
    description: 'Refillable clipper lighter with removable flint system.',
    price: 35,
    stockQuantity: 250,
    imageUrl: '/images/placeholder-product.png',
    imageUrls: ['/images/placeholder-product.png'],
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '38',
    sku: 'PR-008',
    name: 'Silicone Bong - Foldable',
    category: 'paraphernalia',
    description: 'Flexible silicone water pipe, perfect for travel, virtually unbreakable.',
    price: 320,
    stockQuantity: 40,
    imageUrl: '/images/placeholder-product.png',
    imageUrls: ['/images/placeholder-product.png'],
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '39',
    sku: 'PR-009',
    name: 'Ash Tray - Glass',
    category: 'paraphernalia',
    description: 'Heavy glass ashtray with multiple rests and deep bowl.',
    price: 85,
    stockQuantity: 100,
    imageUrl: '/images/placeholder-product.png',
    imageUrls: ['/images/placeholder-product.png'],
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '40',
    sku: 'PR-010',
    name: 'Filter Tips - Natural',
    category: 'paraphernalia',
    description: 'Natural unbleached filter tips, perforated for easy rolling.',
    price: 30,
    stockQuantity: 300,
    imageUrl: '/images/placeholder-product.png',
    imageUrls: ['/images/placeholder-product.png'],
    isActive: true,
    createdAt: new Date().toISOString(),
  },

  // Concentrates (5 products)
  {
    id: '41',
    sku: 'CO-001',
    name: 'Shatter - Golden',
    category: 'concentrates',
    description: 'Pure golden shatter, 85% THC, clean and potent.',
    thcPercentage: 85,
    cbdPercentage: 0.5,
    price: 350,
    stockQuantity: 30,
    imageUrl: '/images/placeholder-product.png',
    imageUrls: ['/images/placeholder-product.png'],
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '42',
    sku: 'CO-002',
    name: 'Live Resin - OG Kush',
    category: 'concentrates',
    description: 'Fresh frozen live resin with full terpene profile, 80% THC.',
    thcPercentage: 80,
    cbdPercentage: 1,
    price: 400,
    stockQuantity: 25,
    imageUrl: '/images/placeholder-product.png',
    imageUrls: ['/images/placeholder-product.png'],
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '43',
    sku: 'CO-003',
    name: 'Wax - Premium',
    category: 'concentrates',
    description: 'Honeycomb wax texture, easy to handle, 78% THC.',
    thcPercentage: 78,
    cbdPercentage: 0.8,
    price: 320,
    stockQuantity: 35,
    imageUrl: '/images/placeholder-product.png',
    imageUrls: ['/images/placeholder-product.png'],
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '44',
    sku: 'CO-004',
    name: 'Rosin - Solventless',
    category: 'concentrates',
    description: 'Pure solventless rosin pressed from premium flower, 75% THC.',
    thcPercentage: 75,
    cbdPercentage: 2,
    price: 450,
    stockQuantity: 20,
    imageUrl: '/images/placeholder-product.png',
    imageUrls: ['/images/placeholder-product.png'],
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '45',
    sku: 'CO-005',
    name: 'Diamonds - THCA',
    category: 'concentrates',
    description: 'Crystalline THCA diamonds in terpene sauce, 90% THC.',
    thcPercentage: 90,
    cbdPercentage: 0.3,
    price: 500,
    stockQuantity: 15,
    imageUrl: '/images/placeholder-product.png',
    imageUrls: ['/images/placeholder-product.png'],
    isActive: true,
    createdAt: new Date().toISOString(),
  },

  // Vapes (5 products)
  {
    id: '46',
    sku: 'VP-001',
    name: 'Vape Pen - Sativa Blend',
    category: 'vapes',
    description: 'Disposable vape pen with energizing sativa terpenes, 500mg THC.',
    thcPercentage: 70,
    cbdPercentage: 0,
    price: 280,
    stockQuantity: 60,
    imageUrl: '/images/placeholder-product.png',
    imageUrls: ['/images/placeholder-product.png'],
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '47',
    sku: 'VP-002',
    name: 'Vape Cartridge - Indica',
    category: 'vapes',
    description: '510 thread cartridge filled with indica oil, 1000mg THC.',
    thcPercentage: 85,
    cbdPercentage: 0,
    price: 350,
    stockQuantity: 50,
    imageUrl: '/images/placeholder-product.png',
    imageUrls: ['/images/placeholder-product.png'],
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '48',
    sku: 'VP-003',
    name: 'CBD Vape - Mint',
    category: 'vapes',
    description: 'Non-psychoactive CBD vape with refreshing mint flavor, 500mg CBD.',
    thcPercentage: 0,
    cbdPercentage: 50,
    price: 250,
    stockQuantity: 70,
    imageUrl: '/images/placeholder-product.png',
    imageUrls: ['/images/placeholder-product.png'],
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '49',
    sku: 'VP-004',
    name: 'Live Resin Cart - Hybrid',
    category: 'vapes',
    description: 'Premium live resin cartridge with full spectrum terpenes, 1000mg THC.',
    thcPercentage: 90,
    cbdPercentage: 0.5,
    price: 420,
    stockQuantity: 40,
    imageUrl: '/images/placeholder-product.png',
    imageUrls: ['/images/placeholder-product.png'],
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '50',
    sku: 'VP-005',
    name: 'Vape Battery - Adjustable',
    category: 'vapes',
    description: 'Variable voltage 510 battery with USB-C charging and preheat function.',
    price: 180,
    stockQuantity: 90,
    imageUrl: '/images/placeholder-product.png',
    imageUrls: ['/images/placeholder-product.png'],
    isActive: true,
    createdAt: new Date().toISOString(),
  },
];
